service:
  name: currencycap-interview

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.getBananaBudget
    events:
      - http:
          method: get
          path: banana-budget
